# Generated by Django 3.2.13 on 2022-07-04 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ftuser',
            fields=[
                ('userid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='유저ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('password', models.CharField(max_length=300, verbose_name='비밀번호')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'cryptolab_ftuser',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('qrcode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('isval', models.BooleanField(default=True)),
                ('id', models.ForeignKey(blank=True, db_column='userid', max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ftuser.ftuser')),
            ],
            options={
                'verbose_name': 'QR',
                'verbose_name_plural': 'QR',
                'db_table': 'cryptolab_location',
            },
        ),
    ]
