# Generated by Django 3.2.13 on 2022-07-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='id',
            field=models.ForeignKey(blank=True, db_column='id', max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ftuser.ftuser'),
        ),
    ]
